### ISSUE TITLE
Use AWS ELB Proxy Protocol

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#100]
Currently, when the CLOUD_PROVIDER is set to aws, a new Service is created for the Ingress of type LoadBalancer by default.

The behavior I desire is for the LoadBalancer Service to use the `"service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"` annotation to enable the Proxy Protocol on the AWS ELB, so that the proper headers like X-Real-IP and X-Forwarded-For are set correctly.

Here are my deployments:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: voyager-operator
  namespace: default
  labels:
    run: voyager-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: voyager-operator
  template:
    metadata:
      labels:
        run: voyager-operator
    spec:
      containers:
      - name: voyager-operator
        image: appscode/voyager:1.5.4
        args:
        - --cloud-provider=$(CLOUD_PROVIDER)
        - --cluster-name=$(CLUSTER_NAME)
        - --v=3
        ports:
        - containerPort: 1234
          name: zero
          protocol: TCP
        env:
        - name: CLOUD_PROVIDER
          value: aws
        - name: CLUSTER_NAME
          value: mcclusterface

---

kind: Service
metadata:
  name: voyager-operator
  namespace: default
  labels:
    run: voyager-operator
spec:
  ports:
  - name: zero
    port: 1234
    targetPort: zero
  selector:
    run: voyager-operator

```
