### ISSUE TITLE
Broken annotations for standard Ingress resource

### ISSUE THREAD

**Issue by miry** [appscode/voyager#1054]
I use 7.0.0-rc.1 version.

I tried to create a standard resource with features https://github.com/appscode/voyager/blob/master/docs/guides/ingress/pod-placement.md#using-node-selector

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: letsencrypt
  annotations:
    kubernetes.io/ingress.class: "voyager"
    ingress.appscode.com/type: HostPort
    ingress.appscode.com/replicas: '1'
    ingress.appscode.com/node-selector: '{"role": "edge"}'
    ingress.appscode.com/tolerations: '[{"key": "IngressOnly", "operator": "Equal", "value": "true", "effect": "NoSchedule"}]'
    ingress.appscode.com/workload-kind: DaemonSet
spec:
  rules:
    - host: 'logs.example.com
      http:
        paths:
        - path: /
          backend:
            serviceName: nginx
            servicePort: 80
```

And got:

```shell
 $ kubectl get daemonset               
NAME                  DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
voyager-letsencrypt   1         1         1         1            1           <none>          1m
```

There is missing tolerations and node selector.
