### ISSUE TITLE
Automate TLS certificate generation

### ISSUE THREAD

**Issue by miry** [appscode/voyager#1055]
Currently it is not possible automate generation of certificates. There is a nice tool cert-manager and here is example how it work with nginx-ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt-staging
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - test.example.com
    secretName: test-staging-letsencrypt
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
```

With voyager it does not work:
-  tls certificate's secret is missing and there are no default/fake one, and haproxy pod always restarts
- node selector and taints annotation does not work for HostPort solution
