### ISSUE TITLE
Basic auth doesn't work 5.0.0-rc.11

### ISSUE THREAD

**Issue by lastonoga** [appscode/voyager#1079]
I am trying to setup basic auth with backend service and it doesn't work.

https://appscode.com/products/voyager/5.0.0-rc.11/guides/ingress/security/basic-auth/

Service yaml is

```
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "stolon-admin",
    "namespace": "default",
    "annotations": {
      "ingress.kubernetes.io/auth-realm": "Test dev",
      "ingress.kubernetes.io/auth-secret": "dashboard-password",
      "ingress.kubernetes.io/auth-type": "basic"
    }
  },
  "spec": {
    "ports": [
      {
        "name": "http",
        "protocol": "TCP",
        "port": 5050,
        "targetPort": 80
      }
    ],
    "selector": {
      "app": "stolon-admin"
    },
    "clusterIP": "10.233.2.169",
    "type": "ClusterIP",
    "sessionAffinity": "None"
  },
  "status": {
    "loadBalancer": {}
  }
}
```

Ingress yaml is
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: dashboards
  namespace: default
  annotations:
    ingress.appscode.com/type: HostPort
    ingress.appscode.com/node-selector: '{ "role": "dashboard-load-balancer" }'
    ingress.appscode.com/replicas: '1'
spec:

  rules:

  - host: wordpress.test.dev
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: "80"

  - host: alerts.test.dev
    http:
      paths:
      - backend:
          serviceName: monitoring-prometheus.monitoring
          servicePort: "9090"

  - host: grafana.test.dev
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana.monitoring
          servicePort: "80"

  - host: pgadmin.test.dev
    http:
      paths:
      - backend:
          serviceName: stolon-admin
          servicePort: "5050"

  - host: loghouse.test.dev
    http:
      paths:
      - backend:
          serviceName: loghouse.loghouse
          servicePort: "80"
```
