### ISSUE TITLE
Updating Ingress annotations are not picked up by controller

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#115]
Currently, when I add or update annotations to my Ingress object, none of the changes are made.

For example, before:

```
apiVersion: appscode.com/v1beta1
kind: Ingress
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  # Default backend
  backend:
    serviceName: echoserver
    servicePort: 80
```

After:
```
apiVersion: appscode.com/v1beta1
kind: Ingress
metadata:
  name: frontend
  labels:
    app: frontend
  annotations:
    # Enable the AWS Proxy Protocol
    # NOTE(jmodes): We need to have `bind :80 accept-proxy` for HAProxy to accept Proxy Protocol requests.
    # ingress.appscode.com/annotations.service: '{"service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"}'
    # Number of HAProxy replicas to run
    ingress.appscode.com/replicas: 1
    # Open HAProxy stats on port 1936
    ingress.appscode.com/stats: true
    ingress.appscode.com/stats.secretName: frontend-stats
spec:
  # Default backend
  backend:
    serviceName: echoserver
    servicePort: 80
```

After applying the new Ingress, none of the changes were enacted by the controller.
