### ISSUE TITLE
RBAC broken in 7.2 if using ClusterRole

### ISSUE THREAD

**Issue by dmegyesi** [appscode/voyager#1163]
In the following file: https://github.com/appscode/voyager/blob/release-7.2/hack/deploy/rbac-list.yaml

There are 2 role definitions at the beginning:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: voyager-operator
  namespace: ${VOYAGER_NAMESPACE}
  labels:
    app: voyager
```

and

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ${VOYAGER_ROLE_TYPE}
metadata:
  name: voyager-operator
  namespace: ${VOYAGER_NAMESPACE}
  labels:
    app: voyager
```

If you use `--restrict-to-namespace=false`, for example, I'm only deploying it in `kube-system`, then the above mentioned parts will overwrite each other, because of this: https://github.com/appscode/voyager/blob/release-7.2/hack/deploy/voyager.sh#L99

Eventually it will render two ClusterRole objects, both at the same name of `voyager-operator`. So first it will apply one definition, then later **overwrite** it with the second one, therefore cancelling the definitions of the first file completely.

Because of this, all of the following permissions are missing:

```
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - voyager.appscode.com
  resources: ["*"]
  verbs: ["list"]
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list", "watch", "get"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["get", "list", "watch"]
```

This causes Voyager to throw tons of API errors, because it cannot query nodes, namespaces, etc.
