### ISSUE TITLE
Support multiple certificates for tls struct

### ISSUE THREAD

**Issue by marksullivancrowd** [appscode/voyager#1167]
In a scenario where you have dedicated loadbalancer in a baremetal setup.
All termination may happen on dedicated ips, so multiple certs are an advantage.
Haproxy supports multiple certs for different domains, however voyager does not seem to be able to define them.
pem files get dropped into /etc/ssl/private/haproxy/tls/

currently the secretName of type string. 

possible tls struct could look something like this.
defining the tls like this is invalid
from this [example](https://appscode.com/products/voyager/7.2.0/guides/certificate/http/overview/#update-ingress-to-use-tls)
```
   - hosts:
     - one.domain1.com
     ref:
       kind: Secret
       name: domain1_tls
     - one.domain2.com
     ref:
       kind: Secret
       name: domain2_tls
```

possible new secretName(s) hash tls struct could look something like this.

```
tls:
 - secretNames: 
      domain1_tls: 
       hosts:
         - one.domain1.com
         - two.domain1.com
      domain2_tls: 
       hosts:
         - one.domain2.com
         - two.domain2.com
```

and would then generate 

```
/etc/ssl/private/haproxy/tls/domain1_tls.pem
/etc/ssl/private/haproxy/tls/domain2_tls.pem
```

**Comment by lrodorigo** [comment]
Same issue here,
these could be really useful.
I succesfully issued two different certificates for two sub-domains 
```tls:
  - hosts:
    - first.domain.com
    ref:
      kind: Certificate
      name: first-certificate
    - second.domain.com
    ref:
      kind: Certificate
      name: second-certificate
```

but ingress changes are rejected with following message:
`The edited file failed validation": [yaml: line 138: did not find expected key, [invalid character 'a' looking for beginning of value, invalid character 'a' looking for beginning of value]]`

**Comment by tamalsaha** [comment]
@lrodorigo, 

```
  - hosts:
    - first.domain.com
    ref:
      kind: Certificate
      name: first-certificate
  - hosts:
    - second.domain.com
    ref:
      kind: Certificate
      name: second-certificate
```

is supported and should work. Can you please share your full ingress yaml?

Thanks.
