### ISSUE TITLE
Supporting multiple hostnames per backend service

### ISSUE THREAD

**Issue by ocdi** [appscode/voyager#1187]
I've looked through all the documentation and it appears that the ingres rules only support a single hostname per rule. Is this correct or is there a way to route multiple domains to a single backend service? I tried to fudge this by how I would like it to run, like this

```
  - host: 
      - example.com
      - www.example.com
      - someotherdomain.com
    http:
      paths:
      - backend:
          serviceName: exampleservice
          servicePort: '443'
```
but as you would expect

```spec.rules.host in body must be of type string: "array"```

Is there an alternate way to list a number of different hostnames?

**Comment by tamalsaha** [comment]
You can repeat it multiple times. That should work.

```
  - host: 
      - example.com
    http:
      paths:
      - backend:
          serviceName: exampleservice
          servicePort: '443'
  - host: 
      - www.example.com
    http:
      paths:
      - backend:
          serviceName: exampleservice
          servicePort: '443'
  - host: 
      - someotherdomain.com
    http:
      paths:
      - backend:
          serviceName: exampleservice
          servicePort: '443'
```

**Comment by ocdi** [comment]
Thanks for your fast response. That is ultimately how I am implementing it, however I also enabled the health check on the backends, which means the configuration it generates is probing the backend for each hostname because it generates a separate hostname for each. It is probably overkill and just relying on a health / readiness check on the kubernetes layer might be better.

**Comment by tamalsaha** [comment]
You can achieve this with Voyager. Set a backend name and then add frontend rules that matches the extra domains. That will result in something similar.

**Comment by ocdi** [comment]
@tamalsaha thank you for your great help 👍 - that suggestion worked (I didn't know you could set a specified backend name and add additional rules like that). :-)

**Comment by tamalsaha** [comment]
:) Can you suggest how do we document it? This is pretty advanced feature and usually used by folks who have prior experience with HAproxy.

**Comment by ocdi** [comment]
Actually documenting this in the form of an example would be very helpful. What I did based on your suggestion was define an explicit backend name and manually crafted the `acl` and `use_backend` for the additional hostnames. What I was looking for in the documentation that I couldn't find was essentially how to do this. You are right, this is my prior haproxy experience kicking in here.

I'd suggest defining a primary hostname as per all the other docs, but for additional hostnames that you may want

1. Add the extra hostnames on the tls section to enable the ssl binding for the certificate
2. Define an explicit backend name
3. Define frontend rules for the ports that it would run on

I imagine it might make sense to reverse the ordering of this to list the backends first, but this is how I 
had it, which worked. Note my backend is using SSL on the webservers also, which requires an annotation on the service to work, so maybe document it with port 80 on that bit.

```
  frontendRules:
    - port: 80
      rules:
      - acl acl_additional.example.com  hdr(host) -i additional.example.com
      - use_backend examplebackend if acl_additional.example.com
    - port: 443
      rules:
      - acl acl_additional.example.com  hdr(host) -i additional.example.com
      - use_backend examplebackend if acl_additional.example.com

  rules:
  - host: example.com
    http:
      paths:
      - backend:
          name: examplebackend 
          serviceName: exampleservice
          servicePort: '443'
```

One bit that is missing is there appears to be a http -> https redirect rule that is added by the default configuration, which I haven't done here, and probably should add. I think if this isn't a common use case, then at least documenting this is good. Otherwise it might be good if host could be an array to generate this config automatically.
