### ISSUE TITLE
Let's Encrypt staging will use dns-01 but production will try TLS-ALPN-01

### ISSUE THREAD

**Issue by kayteh** [appscode/voyager#1244]
On voyager 7.4.0, for a given cert, say
```yaml
apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: examplecom
  namespace: default
spec:
  domains:
  - example.com
  acmeUserSecretName: acme-account-staging
  challengeProvider:
    dns:
      provider: gce
      credentialSecretName: voyager-gce
```
Using LE production, voyager will seem to ignore DNS as a possible challenge, but will try TLS-ALPN-01 in very fast succession, and fail on my config, until it gets rate limited. Logs mention there not being a solver for http-01.

However, with LE staging, voyager will immediately use the DNS challenge and succeed.
