### ISSUE TITLE
Support Services of type ExternalName

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#127]
Currently, Services of type ExternalName are unsupported.

For Services of type ExternalName, it would be great if we could support creating a simple HAProxy redirect rule to the ExternalName.

```
kind: Service
apiVersion: v1
metadata:
  name: foobar
spec:
  ports:
  type: ExternalName
  externalName: new.foobar.com

---

apiVersion: appscode.com/v1beta1
kind: Ingress
metadata:
  name: foobar
  annotations:
    kubernetes.io/ingress.class: voyager
spec:
  rules:
  - host: foobar.com
    http:
      paths:
      - path: '/'
        backend:
          serviceName: foobar
```

haproxy.cfg
```
backend foobar
    http-request redirect location new.foobar.com code 301
```
