### ISSUE TITLE
HAProxy warnings with Backend rules

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#129]
```
[voyager-mysql-user-ingress-fmhzj] daemon.err: May 30 12:56:22 reloader:  [WARNING] 149/142650 (80) : parsing [/etc/haproxy/haproxy.cfg:77] : a 'http-request' rule placed after a 'reqxxx' rule will still be processed before. 
[voyager-mysql-user-ingress-fmhzj] daemon.err: May 30 12:56:22 reloader: [WARNING] 149/142650 (80) : parsing [/etc/haproxy/haproxy.cfg:80] : a 'http-request' rule placed after a 'reqxxx' rule will still be processed before. 
[voyager-mysql-user-ingress-fmhzj] daemon.err: May 30 12:56:22 reloader: [WARNING] 149/142650 (80) : parsing [/etc/haproxy/haproxy.cfg:93] : a 'http-request' rule placed after a 'reqxxx' rule will still be processed before. 
[voyager-mysql-user-ingress-fmhzj] daemon.err: May 30 12:56:22 reloader: [WARNING] 149/142650 (80) : parsing [/etc/haproxy/haproxy.cfg:96] : a 'http-request' rule placed after a 'reqxxx' rule will still be processed before. 
```

**Comment by TamalSaha** [comment]
@skuda, do you mind sharing the relevant part of your ingress rule that produced these warning?

**Comment by skuda** [comment]
Sure, this is the config I am using:

```
apiVersion: appscode.com/v1beta1
kind: Ingress
metadata:
  name: mysql-user-ingress
  annotations:
     ingress.appscode.com/type: HostPort
     ingress.appscode.com/daemon.nodeSelector: "kubernetes.io/hostname=master-03"
     ingress.appscode.com/stats: true
     ingress.appscode.com/stats.secretName: mysql-user-ingress-secret
spec:
  rules:
  - host: phpmyadmin.local
    http:
      paths:
      - path: '/1'
        backend:
          hostNames:
          - mysql-user-0
          serviceName: mysql-user-headless
          servicePort: '80'
          headerRule:
          - X-Forwarded-Host %[req.hdr(Host)]
          - X-Forwarded-Port %[dst_port]
          # - X-Forwarded-Proto https
          rewriteRule:
          - ^(GET|POST|HEAD)\ /1/(.*)     \1\ /\2
          backendRule:
          - 'acl hdr_location res.hdr(Location) -m found'
          - 'rspirep ^Location:\ (https?://phpmyadmin.local(:[0-9]+)?)?(/.*) Location:\ /1/ if hdr_location'
      - path: '/2'
        backend:
          hostNames:
          - mysql-user-1
          serviceName: mysql-user-headless
          servicePort: '80'
          headerRule:
          - X-Forwarded-Host %[req.hdr(Host)]
          - X-Forwarded-Port %[dst_port]
          # - X-Forwarded-Proto https
          rewriteRule:
          - ^(GET|POST|HEAD)\ /2/(.*)     \1\ /\2
          backendRule:
          - 'acl hdr_location res.hdr(Location) -m found'
          - 'rspirep ^Location:\ (https?://phpmyadmin.local(:[0-9]+)?)?(/.*) Location:\ /1/ if hdr_location'
```
