### ISSUE TITLE
Ingress Configuration with URL Redirection

### ISSUE THREAD

**Issue by Tharun-Sabbu** [appscode/voyager#1307]
Hello,

I'm having trouble in configuring jenkins path to use backend service.

Here is the configuration:

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: default
  annotations:
    ingress.appscode.com/type: LoadBalancer
    ingress.appscode.com/annotations-service: |
      {
          "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
      }
    ingress.appscode.com/stats: "true"
    ingress.appscode.com/stats-port: '8081'
    ingress.appscode.com/replicas: '1'
spec:
  rules:
  - host:
    http:
      port: 443
      paths:
      - path: "/jenkins"
        backend:
          serviceName: jenkins-jenkins.default
          servicePort: '8080'
          rewriteRule:
          - ^([^\ ]*\ /)jenkins[/]?(.*)     \1\2
```
I'm having trouble on redirection as it is removing jenkins from path and getting 503,  but if I give only '/'in path:

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: applications-ingress
  namespace: default
  annotations:
    ingress.appscode.com/type: LoadBalancer
    ingress.appscode.com/annotations-service: |
      {
          "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
      }
    ingress.appscode.com/stats: "true"
    ingress.appscode.com/stats-port: '8081'
    ingress.appscode.com/replicas: '1'
spec:
  rules:
  - host:
    http:
      port: 443
      paths:
      - path: "/"
        backend:
          serviceName: jenkins-jenkins.default
          servicePort: '8080' 
```
Only slash is working but want the same ingress to be used for multiple jenkins like this:

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: applications-ingress
  namespace: default
  annotations:
    ingress.appscode.com/type: LoadBalancer
    ingress.appscode.com/annotations-service: |
      {
          "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
      }
    ingress.appscode.com/stats: "true"
    ingress.appscode.com/stats-port: '8081'
    ingress.appscode.com/replicas: '1'
spec:
  rules:
  - host:
    http:
      port: 443
      paths:
      - path: "/jenkins1"
        backend:
          serviceName: jenkins-jenkins1.default
          servicePort: '8080'
      - path: "/jenkins2"
        backend:
          serviceName: jenkins-jenkins2.default
          servicePort: '8080'
```

If I give this way, it's appending to url and messing-up the url which incase getting 503. How do I achieve this?

**Comment by diptadas** [comment]
Hi @Tharun-Sabbu, do you want to rewrite the URL paths before forwarding requests to backends? 

`/jenkins1/rest-of-path` ----> `/rest-of-path` ----> backend: `jenkins-jenkins1.default`
`/jenkins2/rest-of-path` ----> `/rest-of-path` ----> backend: `jenkins-jenkins2.default`

You have a typo in the in the first YAML. You have to use `rewriteRules` instead of `rewriteRule`.

For example:

```YAML
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: applications-ingress
  namespace: default
  annotations:
    ingress.appscode.com/type: LoadBalancer
    ingress.appscode.com/annotations-service: |
      {
          "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
      }
    ingress.appscode.com/stats: "true"
    ingress.appscode.com/stats-port: '8081'
    ingress.appscode.com/replicas: '1'
spec:
  rules:
  - host:
    http:
      port: 443
      paths:
      - path: "/jenkins1"
        backend:
          serviceName: jenkins-jenkins1.default
          servicePort: '8080'
          rewriteRules:
          - ^([^\ ]*\ /)jenkins1[/]?(.*)     \1\2
      - path: "/jenkins2"
        backend:
          serviceName: jenkins-jenkins2.default
          servicePort: '8080'
          rewriteRules:
          - ^([^\ ]*\ /)jenkins2[/]?(.*)     \1\2
```

Please reopen if you are still having this issue.
