### ISSUE TITLE
RBAC issue with helm install

### ISSUE THREAD

**Issue by rajiteh** [appscode/voyager#1333]
I am using the chart version 8.0.1 and looks like it's missing the right RBAC rule for Daemonset workloads.

When I submit an Ingress with Daemonset as the workload type I see the following log on the operator:
```
daemonsets.extensions "voyager-test-tcp-sni" is forbidden: User "system:serviceaccount:default:voyager-voyager-operator" cannot get daemonsets.extensions in the namespace "default"
```

However, after patching the clusterrole with the following:
```
...
- apiGroups:
  - extensions
  resources:
  - ingresses
  - daemonsets #  <-- ADDED 
  verbs:
  - '*'
...
```

Everything proceeds as normal. I'm guessing this clause should be added to the chart?

I'm on Kubernetes 1.10.5 (According to the docs Voyager 8.0.1 is compatible with 1.9.x+)
