### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by joshuacox** [appscode/voyager#1369]
I get many errors like the subject when I try to access a service with voyager + TLS + basic auth.  I often set something like this up when testing out an unsecured service.  My annotations look like this:

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: chart-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: m-htpasswd
    ingress.kubernetes.io/auth-realm: "Authentication Required - m"
spec:
  tls:
  - hosts:
    - example.net
    ref:
      kind: Secret
      name: tls-m
  rules:
  - host: example.net
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: 80
        path: /
```

the important thing to note is that it does work, but I have to clear out all cookies and even then I sometimes still have to wat another 15 minutes before the browser lets me through.  Any ideas about what is going wrong?  Should I be going about this another way?
