### ISSUE TITLE
 Dynamic Ingress in Kubernetes

### ISSUE THREAD

**Issue by mcortinas** [appscode/voyager#1399]
Hi,
 Currently we use voyager as a ingress controller but we need configure backend rules dinamically. 
 I read datawire/ambassador project can do it, [let me share this link to the documentation](https://github.com/datawire/ambassador/blob/master/docs/user-guide/getting-started.md)
[Let me also share this another link to short blog](https://kubernetes.io/blog/2018/06/07/dynamic-ingress-in-kubernetes/)
 
I think this will be useful for voyager.
Let me add an example, currently we can do this:

```apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: ingress-controller-name1
  namespace: ingress-voyager
  annotations:
    kubernetes.io/ingress.class: voyager
spec:
  rules:
  - host: service1.FQDN 
    http:
      paths:
      - path: /
        backend:
          serviceName: endpoint.service1
          servicePort: '80'
```

This will be very useful if we can add backend rules dinamically if we deploy services like this

```
apiVersion: v1
kind: Service
metadata:
  name: endpoint
  namespace: service1
  annotations:
    service.appscode.com/ingress-registration: "ingress-controller-name1"
    service.appscode.com/ingress-namespace-registration: "ingress-voyager"
    service.appscode.com/backend-rule-host: "service1.FQDN"
    service.appscode.com/backend-rule-path: "/"
    service.appscode.com/backend-rule-backend-serviceName: "endpoint.service1"
    service.appscode.com/backend-rule-backend-servicePort: "80"
spec:
  type: ClusterIP
  ports:
    - port: 80
```

Best,
Marc
