### ISSUE TITLE
Support StatefulSet pod names in Voyager

### ISSUE THREAD

**Issue by TamalSaha** [appscode/voyager#14]
Instead of using Pod endpoints, use their stable DNS names if possible.

```yaml
- backend:
    statefulSetName: jenkins-service
    statefulSetPort: "80"
```
