### ISSUE TITLE
Integration issue with Jenkins

### ISSUE THREAD

**Issue by arvind0598** [appscode/voyager#1403]
Hi,

I have three services. Two of them are for jenkins and one is an echo server. One jenkins service runs as a NodePort while the other two services are ClusterIP. I used Voyager to create an Ingress that exposes the ClusterIP services via NodePort, using the following configuration:

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: path-routing
  namespace: default
  annotations:
   ingress.appscode.com/type: NodePort
   ingress.appscode.com/rewrite-target: /
spec:
  rules:
  - host: '*'
    http:
      nodePort: 30733
      paths:
      - path: /jenkins
        backend:
         serviceName: jenkins
         servicePort: 8080
      - path: /other
        backend:
          serviceName: sample-echo
          servicePort: 8001
```

I am able to access the NodePort exposed Jenkins service in the browser by a first 403 and then a 200. The echo server also responds correctly by redirecting /other to / and giving a 200 OK response. 

However, on accessing the /jenkins route the service gives 403 and then 503 "No server is available to handle this request."

I assume this is not a Jenkins issue and is a Voyager issue as the NodePort exposed service returned a 200 at the end.

These are the logs during the time the routing service was accessed:

```
I0603 05:12:38.288152      12 reload.go:44] haproxy daemon running (pid 88)

local0.info: Jun  3 05:12:55 haproxy[88]: 192.168.64.192:62896 [03/Jun/2019:05:12:55.457] http-0_0_0_0-80 jenkins.default:8080/pod-jenkins-86c8fb97c7-vdqkw 0/0/0/5/5 403 1265 - - ---- 1/1/0/0/0 0/0 "GET /jenkins HTTP/1.1"

local0.info: Jun  3 05:12:55 haproxy[88]: 192.168.64.192:62896 [03/Jun/2019:05:12:55.648] http-0_0_0_0-80 http-0_0_0_0-80/<NOSRV> -1/-1/-1/-1/0 503 212 - - SC-- 1/1/0/0/0 0/0 "GET /login?from=%2F HTTP/1.1"

local0.info: Jun  3 05:12:56 haproxy[88]: 192.168.64.192:62897 [03/Jun/2019:05:12:56.143] http-0_0_0_0-80 http-0_0_0_0-80/<NOSRV> -1/-1/-1/-1/0 503 212 - - SC-- 1/1/0/0/0 0/0 "GET /favicon.ico HTTP/1.1"

I060 05:13:08.288115      12 reload.go:44] haproxy daemon running (pid 88)
```
