### ISSUE TITLE
ServiceMonitor endpoint path created with the wrong APISchemaIngress (typo?)

### ISSUE THREAD

**Issue by ttauveron** [appscode/voyager#1451]
Hi!

I am creating a `extensions/v1beta1` ingress resource with the `kubernetes.io/ingress.class: voyager` annotation :

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test334
  namespace: test-system
  annotations:
    kubernetes.io/ingress.class: voyager
    ingress.appscode.com/stats: 'true'
    ingress.appscode.com/monitoring-agent: 'prometheus.io/coreos-operator'
    ingress.appscode.com/service-monitor-namespace: 'test-system'
spec:
  tls:
    - secretName: tls-certificate-wildcard-test
      hosts:
      - test334.test.io
  rules:
  - host: test334.test.io
    http:
      paths:
      - backend:
          serviceName: my-service2
          servicePort: 80
```

Then the following ServiceMonitor is automatically created : 

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring.appscode.com/service: voyager-test334-stats.test-system
  name: voyager-test-system-test334
  namespace: test-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    kind: Service
    name: voyager-test334-stats
spec:
  endpoints:
  - honorLabels: true
    path: /extension/v1beta1/namespaces/test-system/ingresses/test334/metrics
    port: http
  namespaceSelector:
    matchNames:
    - test-system
  selector:
    matchLabels:
      feature: stats
      origin: voyager
      origin-api-group: extension
      origin-name: test334
```
The problem is that I get a 404 error in the Prometheus target because of the path : an `s` is missing in `extension/v1beta1`
```diff
- extension/v1beta1/namespaces/[...]
+ extensions/v1beta1/namespaces/[...]
```

I don't get this error when I use the `voyager.appscode.com/v1beta1` ingress CRD.

I think this might be due to a typo in here : 
https://github.com/appscode/voyager/blob/master/apis/voyager/v1beta1/annotations.go#L39

What do you think?

Thank you!
