### ISSUE TITLE
Voyager sent down the entire app deployed in the cluster

### ISSUE THREAD

**Issue by mazzy89** [appscode/voyager#1462]
This is a very interesting story and perhaps one of the very nasty bug I stumbled upon.

We run ku8s 1.15.6 and I have deployed Voyager 9.0.0 with the following config `values.yaml` in `kube-system`.

```
    ##
    ## Voyager chart configuration
    ##
    replicaCount: 3

    cloudProvider: aws
    ## Log level for voyager
    logLevel: 5

    # this flag can be set to 'voyager' to handle only ingress
    # with annotation kubernetes.io/ingress.class=voyager.
    ingressClass: "voyager"

    apiserver:
      # enableValidatingWebhook is used to configure apiserver as ValidationWebhook for Voyager CRDs
      enableValidatingWebhook: false
      # If true, bypasses validating webhook xray checks
      bypassValidatingWebhookXray: true

    # Send usage events to Google Analytics
    enableAnalytics: false
```

We deploy a Voyager Ingress in the `default` namespace along with other `Ingress` and `Service`(s).

Funny bug. Once we kill a voyager pod running the `kube-system` all the `Services` in the default namespace are deleted. Result. App down 🙀
