### ISSUE TITLE
Ensure that the Ingress's Service is re-created and exists if it's deleted

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#186]
If you delete the Service for your ingress e.g. with `kubectl delete service voyager-example`, then it's not created by the controller.

**Comment by TamalSaha** [comment]
@julianvmodesto , which version of Voyager are you using?

**Comment by TamalSaha** [comment]
This was addressed in https://github.com/appscode/voyager/pull/145

**Comment by TamalSaha** [comment]
@julianvmodesto , do you still see this issue with 1.5.6?

**Comment by julianvmodesto** [comment]
I believe so, but I'll verify one again to make sure

**Comment by sadlil** [comment]
The service should recreated if its deleted by hand.

**Comment by julianvmodesto** [comment]
Thanks @sadlil.

For some reason, I'm still seeing no service after running the deletion below. Should the recreation be immediate, or is there some delay time?

```
$ kubectl delete svc voyager-grafana
service "voyager-grafana" deleted
```

My Ingress definition
```
apiVersion: appscode.com/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: grafana
  labels:
    app: grafana
  annotations:
    # Use the Voyager Ingress Controller
    kubernetes.io/ingress.class: voyager
spec:
  # Default backend
  backend:
    serviceName: grafana
    servicePort: 80
  loadBalancerSourceRanges:
...
```

Voyager version
```
$ kubectl exec --namespace=kube-system voyager-operator-1489841599-2vwkb /voyager version
Version = 1.5.6
VersionStrategy = tag
Os = linux
Arch = amd64
CommitHash = c7a6bb6a1435b949938f5e5e4034193d1dfb320b
GitBranch = release-1.5
GitTag = 1.5.6
CommitTimestamp = 2017-06-16T12:21:07
BuildTimestamp = 2017-06-16T12:23:35.026818
BuildHost = beast
BuildHostOs = linux
BuildHostArch = amd64
```
