### ISSUE TITLE
Generate host based on template

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#240]
```
  - host: 'tenant-${1}.appscode.ninja'
    http:
      - backend:
          hostNameRegex: web-(.+)
          serviceName: pharm
          servicePort: "80"
```

An ingress like above will route traffic like below:

 * tenant-0.example.com ---> web-0
 * tenant-1.example.com ---> web-1
...
 so on

cc: yalos

**Comment by tamalsaha** [comment]
cc: @yalos

**Comment by tamalsaha** [comment]
I think a better approach will be to do something like https://github.com/appscode/voyager/issues/600

On StatefulSets, user can apply annotations like:
```

**Comment by tamalsaha** [comment]
Another idea based on conversation with Gavin Zhou in Slack;

User writes:
```
- host: "%s.example.com"
  values:
  - web
  - ui
  - api
  http:
    paths:
	- backend:
	    serviceName: "%s"
	    servicePort: "80"
```

Voyager operator expands that into 

```
- host: "web.example.com"
  http:
    paths:
	- backend:
	    serviceName: "web"
	    servicePort: "80"
- host: "ui.example.com"
  http:
    paths:
	- backend:
	    serviceName: "ui"
	    servicePort: "80"
- host: "api.example.com"
  http:
    paths:
	- backend:
	    serviceName: "api"
	    servicePort: "80"
```
