### ISSUE TITLE
voyager with ingress in multiple namespaces

### ISSUE THREAD

**Issue by fvigotti** [appscode/voyager#305]
I wrote this here because this seems not documented and may be useful to someone else looking for the same information:
After the main application has been deployed ( the one with the image: appscode/voyager:3.0.0 )  this application read ingress configuration and create a deployment, allowing customization by passing some configuration parameters in ingress -> metadata.annotations.*

When multiple ingress (in different namespaces ) are create this **behaviour** seems differentiate from the default kubernetes ingress controller, because voyager create a new deployment in those new namespaces,

obviously this must be taken in consideration and should be documented because is not always wanted, 
because this means ( at least on bare-metal servers ) that it's not possible for voyager expose on same ip address + same port  ( but different domain/path/.. ) two services on different namespaces ( while this is possible with kubernetes-nginx ingresscontroller ) 

I am right?
Thank you,
Francesco

**Comment by fvigotti** [comment]
Maybe I've found a solution,
Using external service ( https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/external-svc.md ) to point against services in other namespaces,
this way I can have a single ingress controller to serve services from multiple namespaces even if it's a bit verbose  to write :)

If there is a better approach let me know :)

Thanks,
Francesco

**Comment by sadlil** [comment]
If your use case is simply reference an service from another namespace. You can simply add that as backend service. 
```yaml
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: foo   // this ingress is in namespace foo
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: serviceName.serviceNamespace  # dot seperated name and namespace of service.
          servicePort: "80" 
```

Read this. https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/named-virtual-hosting.md#cross-namespace-traffic-routing
