### ISSUE TITLE
tcp loadBalancing doesn't get configured? also two syntax documented

### ISSUE THREAD

**Issue by fvigotti** [appscode/voyager#307]
Hi, there are documented two syntax for TCP 

here: https://github.com/appscode/voyager/blob/3.0.0/docs/user-guide/ingress/tcp.md  
```yaml
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
spec:
  rules:
  - tcp:
    - host: appscode.example.com
      port: '9898'
      backend:
        serviceName: tcp-service
        servicePort: '50077'
```

and here: https://github.com/appscode/voyager/blob/master/hack/example/ingress.yaml  
```yaml
  - host: api.example.com
    tcp:
    - backend:
        serviceName: apiserver
        servicePort: "50077"
      port: "3443"
      secretName: cert-example-com
```

 which is the correct way to configure tcp loadbalancing?

seems that both works (at least create configuration in ha proxy.. ) I'm still trying to access the service from outside.... does the "host" have sense when we are loadbalancing tcp directly ? how gets identified from the stream ?

Thanks ,
Francesco

**Comment by sadlil** [comment]
The proper format is of TCP is
```
  - host: bar.example.com
    tcp:
    - backend:
        serviceName: apiserver
        servicePort: "50077"
      port: "3443"
      secretName: cert-example-com
  - host: foo.example.com
    tcp:
    - backend:
        serviceName: example-apis
        servicePort: "50066"
      port: "3553"
```
https://github.com/appscode/voyager/blob/master/api/ingress.go#L144
The doc needs to update for your first example. Bad from our side. 

The host field have no specific effect in TCP. Its just there to maintain formatting with HTTP rules.
