### ISSUE TITLE
how to use "ingress.appscode.com/node-selector"?

### ISSUE THREAD

**Issue by fvigotti** [appscode/voyager#308]
I've asked this in another issue #303  but maybe I wrote to many things there and it's better to have more contextualized questions..

so,
how to use `ingress.appscode.com/node-selector` ? the guide say that it's a `map` but seems to not work for me and there are no examples at all in whole github.com site nor in google..

thank you,
Francesco

**Comment by tamalsaha** [comment]
Hi,
Can you show us what you have tried? Also, which cloud provider are you using? Are you using GKE / ACS / kops etc?

An example is:
```yaml
ingress.appscode.com/node-selector: '{"kuberntes.io/hostname": "node-xyz"}'

```

**Comment by tlvenn** [comment]
I can't get this to work either with voyager 10.
I have the following annotations:
```
  annotations:
    ingress.appscode.com/workload-kind: DaemonSet
    ingress.appscode.com/type: HostPort
    ingress.appscode.com/node-selector: '{"edgeproxy": "true"}'
```

Some nodes in my cluster have the label `edgeproxy` set to `true` yet haproxy is being started on all the nodes.
