### ISSUE TITLE
Open port 443 in HTTP mode

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#333]
From "ronenf" in our slack channel:

Hi I am having problems getting my app running on port 443. Here part of the ingress:
```
- host: cvc-dev.vatit.io
   http:
     paths:
     - path: /
       backend:
         serviceName: vatit-cvc-dev.vatit-cvc-dev
         servicePort: 443
```

heres the service:
```
spec:
 selector:
     app: vatit-cvc-dev
 ports:
   - port: 443
     targetPort: 443
     name: https
   - port: 80
     targetPort: 80
     name: http
```

The cert is built into the app. I can hit the app on port 80 (It just returns an error saying i cant comunicate https over http). With https infront of the url i cant hit it.
