### ISSUE TITLE
Test aws cert manager 80->443 redirect

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#353]
https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/aws-cert-manager.md

```
- host: cvc-dev.example.com
   http:
     paths:
     - backend:
         serviceName: vatit-cvc-dev.example.dev
         servicePort: 443
         backendRule:
           - ‘acl is_proxy_https hdr(X-Forwarded-Proto) https’
           - ‘redirect scheme https code 301 if ! is_proxy_https’
```
Use is using:
`"service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:eu-west...`

Just `https` works without the backend rule. If the backend rule is added, nothing works.
