### ISSUE TITLE
Static nodeport configuration  for ingress resourse 

### ISSUE THREAD

**Issue by izutheo** [appscode/voyager#400]
Hi all,
 I  just pull the latest version with the static nodeport assignment functionality  fixed.  Unfortunately i still cannot configure the ingress resource to assign a specific port to the type: nodeport. Is there a documentation for this ?

**Comment by tamalsaha** [comment]
Hi, this feature has been implemented in master and will be part of 3.2.0 release. We are yet to update the docs. If you want to test it out, you can use the image tag `appscode/voyager:3.2.0-beta.2` . This is what an example Ingress looks like:
```

**Comment by izutheo** [comment]
Perfect thank you very much

**Comment by izutheo** [comment]
Hi tamalsaha,

I think i might jumped the gone on this, but i was actually asking if there was a way to set a static port for the ingress resource above and not have the port change every time i update the ingress resource.


so following your example above, If i updated the ingress resource with an additional path 



apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: default
  annotations:
    ingress.appscode.com/type: NodePort
spec:
  rules:
  - host:
    http:
      paths: /test
      - backend:
          serviceName: test-server
          servicePort: 80
          nodePort: 32068
    paths: /testing
      - backend:
          serviceName: test-server-2
          servicePort: 80
  So i am basically asking for the ability to have one static port for entry into the cluster and not to a service.

**Comment by tamalsaha** [comment]
@izutheo , sorry I misspoke last time. You can only set one static port for each HAProxy port (which is the entry to the cluster). If you look at the Go struct, the `nodePort` is set for a host:port combination.
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: default
  annotations:
    ingress.appscode.com/type: NodePort
spec:
  rules:
  - host:
    http:
      nodePort: 32068
      paths:
      - path: /t1
        backend:
          serviceName: t1-server
          servicePort: 80
      - path: /t2
        backend:
          serviceName: t2-server
          servicePort: 80
```
