### ISSUE TITLE
zone-specific static IP on gke rather than global static

### ISSUE THREAD

**Issue by kiessan** [appscode/voyager#414]
Hi folks,
I am running a Kubernetes cluster on gke. Within my ingress, i defined a static IP by using the following annotation.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress
  annotations:
    kubernetes.io/ingress.class: voyager
    ingress.appscode.com/load-balancer-ip: 35.186.***.***
spec:
  tls:
  - secretName: test-tls
    hosts:
      - foo.bar.com
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: echoserver
          servicePort: 8080
```

The Kubernetes cluster is running version 1.6.7. When I assign a zone-specific static IP, it works like a charm. However, when assiging a global static IP, the automatically spawned service remains in a pending state forever.

![screenshot_ip](https://user-images.githubusercontent.com/6169762/29623173-d126c13c-8825-11e7-90ca-2ff55e764b94.png)

Does anybody have an idea what could be the reason behind this behaviour? Other proxies such as traefik require a global static IP.

Best wishes, Chris
