### ISSUE TITLE
Ingress validation error

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#420]
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.appscode.com/type: HostPort
    ingress.appscode.com/replicas: '1'
    ingress.appscode.com/node-selector: '{ "node-role.kubernetes.io/master" : "true" }'
  name: "nginx-ingress-app1"
  namespace: default
spec:
  tls:
  - secretName: 'voyager-cert'
    hosts:
    - minicluster.redblackbox.ml
  rules:
  - host: "minicluster.redblackbox.ml"
    http:
      paths:
      - backend:
          serviceName: cluster-nginx
          servicePort: '80'
  - host: "minicluster.redblackbox.ml"
    http:
      noTLS: true
      paths:
      - backend:
          serviceName: cluster-nginx
          servicePort: '80'
#--- BEGIN ANSIBLE MANAGED BLOCK - ALIASES -->
  - host: "domain1.com"
    http:
      paths:
      - backend:
          serviceName: cluster-nginx
          servicePort: 80
  - host: "domain2.com"
    http:
      paths:
      - backend:
          serviceName: cluster-nginx
          servicePort: 80
#--- END ANSIBLE MANAGED BLOCK - ALIASES -->
```

which is giving the following error, which I don’t understand why:

```  10m        10m        1    voyager operator            Warning        IngressInvalid    Reason: spec.rule[2].http.paths[0] is reusing path { {{[] cluster-nginx {%!s(intstr.Type=0) %!s(int32=80) } []} [] []}} for addr minicluster.redblackbox.ml:80, also used in spec.rule[2].http.paths[0]```
