### ISSUE TITLE
unable to decode "voyager/certificate.yaml": no kind "Certificate" is registered for version "appscode.com/v1beta1"

### ISSUE THREAD

**Issue by Joshuabaker2** [appscode/voyager#49]
So I followed the getting started guide, but am running into some errors when trying to deploy. First, my yamls: 

resources.yaml
```
# following https://github.com/appscode/voyager/blob/master/docs/user-guide/README.md
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: ingress.appscode.com
description: "Extended ingress support for Kubernetes by appscode.com"
versions:
  - name: v1beta1

--- 
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: certificate.appscode.com
description: "A specification of a Let's Encrypt Certificate to manage."
versions:
  - name: v1beta1
```

ingress.yaml
```
apiVersion: appscode.com/v1beta1
kind: Ingress
metadata:
  name: voyager-ingress
  namespace: default
spec:
  rules:
  - host: mydomain.com
    http:
      paths:
      - path: "/*"
        backend:
          serviceName: service1
          servicePort: '8282'
  - host: myotherdomain.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: service2
          servicePort: '8484'
```

deployment.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: appscode-voyager
  name: appscode-voyager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: appscode-voyager
  template:
    metadata:
      labels:
        run: appscode-voyager
    spec:
      containers:
      - name: appscode-voyager
        args:
        - --cloud-provider=gke
        - --cluster-name=myclustername
        image: appscode/voyager:1.5.1
        imagePullPolicy: Always
```

certificate.yaml
```
apiVersion: appscode.com/v1beta1
kind: Certificate
metadata:
  name: voyager-cert
  namespace: default
spec:
  domains:
  - mydomain.com
  - myotherdomain.com
  email: myemail@gmail.com
  provider: googlecloud
  providerCredentialSecretName: test-gcp-secret
```

One thing of note is that I'm not sure what the `providerCredentialSecretName` should be. I'm using the google container engine, but wasn't able to find exactly what should go in there, but I don't think that's causing the issue I'm seeing. 

So anyways, I use 
`kubectl apply -f directory_containing_all_these_files/`

and the output I get is: 

```
deployment "appscode-voyager" configured
thirdpartyresource "ingress.appscode.com" configured
thirdpartyresource "certificate.appscode.com" configured
unable to decode "voyager/certificate.yaml": no kind "Certificate" is registered for version "appscode.com/v1beta1"
unable to decode "voyager/ingress.yaml": no kind "Ingress" is registered for version "appscode.com/v1beta1"
```

Is there a step I skipped?
