### ISSUE TITLE
Redesign Certificate CRD

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#505]
```
spec:
  acmeUserSecretName:
  chanlleger:
	http:
	  ingress: {}
	dns:
	  cloud: gce
	  credentialSec
  storage:
    secret:
      name:
    vault:
      name:
      prefix: prod-cluster
```
Status:
https://github.com/kubernetes/api/blob/e24ed681f56165befbea50a24f7e9f1c079ac366/certificates/v1beta1/types.go#L83
