### ISSUE TITLE
Document default mode does not work for minikube

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#545]
IP stays pending for minikube Loadbalancer Ingress.

**Comment by bradenwright** [comment]
Any update or workaround for this, I'm having the same issue

**Comment by tamalsaha** [comment]
@bradenwright, this works fine. If you use LoadBalancer type (the default type), it will only allocate NodePort. You can access the HAProxy pods using `minikube ip`. Does that make sense?

**Comment by bradenwright** [comment]
Hmm maybe I doing something wrong.  I installed into minikube via:

`helm install stable/voyager --set ingressClass=voyager --set cloudProvider=minikube`
`helm install dlf` <-- local helm chart which I can port forward to, ingress from chart is below

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: voyager-ingress
  namespace: default
  kubernetes.io/ingress.class: "voyager"
spec:
  rules:
  - host: dlf.example.com
    tcp:
      port: '20514'
      backend:
        serviceName: {{ .Release.Name }}-dlf
        servicePort: '10514'
```

It rsyslog, which has logs being forwarded to it from remote hosts.  If I port-forward to the pod 10514, and `telnet localhost 10514` telnet connects.

I've set a host record for dlf.example.com -> `minikube ip` which I've successful done with nginx http ingress before.  But I getting in this case I keep getting:

```
$ telnet dlf.example.com 20514
Trying 192.168.99.101...
telnet: connect to address 192.168.99.101: Operation timed out
telnet: Unable to connect to remote host
```

```
$ kc get all
NAME                                                       READY     STATUS    RESTARTS   AGE
po/plundering-pike-dlf-4016503386-fhxxt                         0/1       Running   0          9s
po/voyager-voyager-ingress-1034212999-p578r                1/1       Running   0          9s
po/voyager-xrayed-stoat-4046991754-29h43                   1/1       Running   0          48m

NAME                                       CLUSTER-IP   EXTERNAL-IP   PORT(S)           AGE
svc/kubernetes                             10.0.0.1     <none>        443/TCP           1d
svc/plundering-pike-dlf                   10.0.0.78    <none>        10514/TCP         9s
svc/voyager-voyager-ingress                10.0.0.103   <pending>     20514:30849/TCP   8s
svc/voyager-xrayed-stoat                   10.0.0.25    <none>        56790/TCP         48m

NAME                                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/plundering-pike-dlf .                       1         1         1            0           9s
deploy/voyager-voyager-ingress                1         1         1            1           9s
deploy/voyager-xrayed-stoat                   1         1         1            1           48m

NAME                                                 DESIRED   CURRENT   READY     AGE
rs/plundering-pike-dlf-4016503386                       1         1         0         9s
rs/voyager-voyager-ingress-1034212999                1         1         1         9s
rs/voyager-xrayed-stoat-4046991754                   1         1         1         48m
```

I noticed the pending line so I thought that was related.

**Comment by tamalsaha** [comment]
I suppose, you are referring to 
```
svc/voyager-voyager-ingress                10.0.0.103   <pending>     20514:30849/TCP   8s
```

It stays in pending because the Service `voyager-voyager-ingress` has type `LoadBalancer` and minikube will only allocate the NodePort (: 30849). You can safely ignore this `pending` EXTERNAL_IP and just use the `$(minikube ip):30849` .

If you want to not have this pending thing showing, you can tell voyager to create a `NodePort` type service. To do that use add the `ingress.appscode.com/type: NodePort` annotation.

```yaml
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: voyager-ingress
  namespace: default
  kubernetes.io/ingress.class: "voyager"
  annotations:
    ingress.appscode.com/type: NodePort
spec:
  rules:
  - host: dlf.example.com
    tcp:
      port: '20514'
      backend:
        serviceName: {{ .Release.Name }}-dlf
        servicePort: '10514'
```

**Comment by bradenwright** [comment]
I did notice I put the ingress.class in the wrong place, but I had tried it without that.  That setting helps remove the "pending"

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: voyager-ingress
  namespace: default
  annotations:
    ingress.appscode.com/type: NodePort
    kubernetes.io/ingress.class: voyager
spec:
  rules:
  - host: dlf.example.com
    tcp:
      port: '20514'
      backend:
        serviceName: {{ .Release.Name }}-dlf
        servicePort: '10514'
```

But I can't connect via telnet: `telnet dlf.example.com 30849` or `telnet dlf.example.com 20514` dlf.example.com == minikube ip, I did also try `telnet 192.168.99.101 30849`
