### ISSUE TITLE
certs is not creating secret with ssl certs (LE)

### ISSUE THREAD

**Issue by jalberto** [appscode/voyager#578]
k8s: 1.7.2 acs-engine
voyager: 3.2.1 (installed from helm in this repo with rbac)

1. install voyager with helm
2. create LB
3. create cert object
4. `acme-gandi-certs` is created with `user-info` key
5. go to https://foo.bar.com

Logs:
```
I1005 21:20:51.542707       1 controller.go:225] trying to retrive acmeUser data
I1005 21:20:51.788689       1 controller.go:252] ACMEUserInfo data found is secretacme-gandi-certs
I1005 21:20:52.510209       1 ingress_tprs.go:69] voyager.appscode.com/v1beta1, Kind=Ingress haproxy@default has changed
```

Loadbalancer:
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: haproxy
  namespace: default
  annotations:
    ingress.appscode.com/default-timeout: '{"connect": "5s", "server": "10s"}'
    ingress.appscode.com/default-options: '{"http-keep-alive": "true"}'
    ingress.appscode.com/load-balancer-ip: 'x.x.x.x'
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: gitlab-ce.infra
          servicePort: "80"
          headerRule:
          - X-Forwarded-Host %[base]
  tls:
    - secretName: cert-gandi-certs
      hosts:
      - '*.bar.com'
```

Cert obj:
```
apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: gandi-certs
  namespace: default
spec:
  domains:
  - '*.bar.com'
  email: "ja+le@bar.com"
  provider: http
  httpProviderIngressReference:
    apiVersion: voyager.appscode.com/v1beta1
    kind: Ingress
    Namespace: default
    Name: haproxy
```
