### ISSUE TITLE
Allow for binding frontends to specific addresses

### ISSUE THREAD

**Issue by deuill** [appscode/voyager#602]
This is both a question and a sort of request for help.

I'm running Kubernetes on a single-node cluster (using Minikube) as a means of better orchestrating deployments, and have been trying to integrate Voyager as an ingress for both HTTP and TCP services. My use-case is fairly peculiar since I'm not running behind any kind of load-balancer, and as such am relegated to using `type: HostPort` (which is fine), but also I wish to segregate services types (web-related, mail, chat, etc) into separate IP addresses, of which I have a small number allocated.

To give you a better picture, I segregate services by type into different namespaces, but use Voyager as a means of handling ingress traffic and terminating TLS for all services that allow communication to the outside world. A sample `Ingress` deployment might look like:

```yaml
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  labels:
    app: voyager
  annotations:
    ingress.appscode.com/type: HostPort
spec:
  rules:
    - host: deuill.org
      http:
        address: 203.0.113.101
        paths:
          - backend:
              serviceName: deuill.web
              servicePort: 80
    - host: mail.deuill.org
      tcp:
        address: 203.0.113.102
        port: 25
        backend:
          serviceName: postfix.mail
          servicePort: 25
```
What I'm essentially looking for, as alluded by specifying `address` in the configuration above, is a way of specifying the address to bind on for the underlying HAProxy frontends. Currently, HAProxy is set to bind on all interfaces (i.e. `*`) and the port number specified (defaulting to `80`/`443` for HTTP rules).

I've been working on getting a patch [here](https://github.com/deuill/voyager/commit/4cd7e2908162b5d948049b1123f5420f1d276d47), for my use at least, but cannot seem to find a way of getting the values through.

So, a number of questions:
  - Is this a feature you'd see merging in, i.e. does it make sense as a broader solution?
  - If not, is there a better way you can see this working (network policies etc)?
  - If yes, am I missing something in my patch that would prevent these values passing through?

Thank you in advance!
