### ISSUE TITLE
Is there a way to add any rule in default section

### ISSUE THREAD

**Issue by diwakar-s-maurya** [appscode/voyager#624]
I want to send a unique string in header to backend for every request. The below configuration is works fine

```yaml
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
spec:
  frontendRules:
  - port: 80  # Applies all the rule in frontend section for port 80
    rules:
    - unique-id-header X-Unique-ID
    - unique-id-format %{+X}o\ %ci:%cp_%fi:%fp_%Ts_%rt:%pid
    - log-format %ci:%cp\ [%t]\ %ft\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %ST\ %B\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ %{+Q}r\ %ID
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: echoserver
          servicePort: '8080'
```

The rules `unique-id-header`, `unique-id-format` and `log-format` will apply only to one particular frontend.
Is there a way to move these rules in default section of haproxy configmap so that they get applied to every other frontend and I don't have to repeat the rules again for other frontends?
[This](https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/configure-options.md) supports only the `option` config of haproxy.
