### ISSUE TITLE
Support imagePullSecrets for HAProxy pods

### ISSUE THREAD

**Issue by Hiruma31** [appscode/voyager#673]
Hello,

As mentioned on slack, I can't pull the HAProxy image from my internal registry since hub.docker.com isn't reachable from my cluster.

I specify the image using `--haproxy-image=$MY_REGISTRY/voyager/haproxy:1.7.9-5.0.0-rc.1` in Voyager's deployment. However, when an Ingress is created and the voyager-$INGRESS deployment  pod starts, it tries to pull the said image from the registry, but fails since it doesn't have the imagePullSecret.

Thanks again !

**Comment by tamalsaha** [comment]
This has been added to 5.0.0-rc.3. Please give it a shot.

To use your private image as voyager operator and sidecar exporter, use [flags](https://github.com/appscode/voyager/blob/master/docs/reference/voyager_run.md):
```
--exporter-sidecar-image string         Docker image containing Prometheus exporter (default "appscode/voyager:5.0.0-rc.3")
--haproxy-image string                  Docker image containing HAProxy binary (default "appscode/haproxy:1.7.9-5.0.0-rc.3")
```

To pass imagePullSecrets, set it in the Ingress spec:
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    ingress.appscode.com/type: NodePort
    ingress.appscode.com/force-service-port: "false"
    ingress.appscode.com/stats: "true"
spec:
  imagePullSecrets:
    - name: my-registry-auth
  rules:
  - http:
      - path: /
        backend:
          serviceName: test-server
          servicePort: 80
```
