### ISSUE TITLE
expose NodePort like functionality to Ingress

### ISSUE THREAD

**Issue by skuda** [appscode/voyager#68]
When you are using Voyager with CLOUD_PROVIDER=null because you are using it on baremetal, or maybe DigitalOcean, Voyager allows you to use these annotations:
```
ingress.appscode.com/type: Daemon
ingress.appscode.com/daemon.nodeSelector: "kubernetes.io/hostname=foo"
````

Then when the daemonset starts in the selected node it automatically binds to the tcp port 80, that makes obviously sense, but it would be great if the user is able to use NodePort as well as an alternative.

For example in our case we have a four node cluster in our hosting provider so I only have 4 available ports to use with Voyager but I have thousands of free ports that I would like to use with Voyager and Nodeport.

Thanks!

**Comment by TamalSaha** [comment]
@skuda , I am bit confused by this part of your issue:
`Then when the daemonset starts in the selected node it automatically binds to the tcp port 80, that makes obviously sense, but it would be great if the user is able to use NodePort as well as an alternative.`

In DaemonSet mode, HAProxy is running with hostNetwork = true. For HTTP ingress, Voyager will only bind HAProxy to port 80 or 443. But for TPC ingress, Voyager will bind HAProxy to any port on that node. Does that solve your use-case?

**Comment by skuda** [comment]
for L4 ingress, yes, but I am speaking about L7 ingress, we have lots of micro-services for example, I wouldn't like to expose all of them in 4 HAProxy, one per node.

I even prefer to expose most of our backend apis in non default ports, just for security purposes.

**Comment by TamalSaha** [comment]
We will look into this.

**Comment by TamalSaha** [comment]
@skuda , I think one option we can take is allow users to specify port for L7 ingress. Example:
```
apiVersion: appscode/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - http:
      port: <non-standard-port>
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```
Do you think that will suffice your use-case?
