### ISSUE TITLE
Support ExternalIPs

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#686]
https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

This can be used in bare metal cluster as user managed VIPs.

**Comment by tamalsaha** [comment]
@fvigotti, can you please try the image `appscode/voyager:eip` . You can use an Ingress like below to pass `externalIPs`

```yaml
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: testi
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: voyager
    ingress.appscode.com/type: NodePort
spec:
  externalIPs:
  - xxxxxxxxxxxxxxx
  rules:
  - host: echoheaders.xxxxx
    http:
      paths:
      - backend:
          serviceName: echoheaders
          servicePort: '80'
```
