### ISSUE TITLE
Adding annotation `ingress.kubernetes.io/hsts` makes voyager generate invalid haproxy config

### ISSUE THREAD

**Issue by leonth** [appscode/voyager#701]
I have the following config:
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: core-ingress
  annotations:
    kubernetes.io/ingress.class: voyager
    ingress.appscode.com/type: LoadBalancer
    ingress.appscode.com/load-balancer-ip: "[some.ip]"
    ingress.appscode.com/stats: "true"
    ingress.appscode.com/stats-port: 56789
    ingress.appscode.com/stats-secret-name: core-ingress-stats-creds
    ingress.kubernetes.io/hsts: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
```

This fails to start:
```
 daemon.err: Nov 13 09:15:18 reloader:  [ALERT] 316/091550 (54) : parsing [/etc/haproxy/haproxy.cfg:74] : 'rsprep' : Expecting nothing, 'if', or 'unless', got 'http'.
daemon.err: Nov 13 09:15:18 reloader: [ALERT] 316/091550 (54) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
daemon.err: Nov 13 09:15:18 reloader: [ALERT] 316/091550 (54) : Fatal errors found in configuration.
daemon.err: Nov 13 09:15:18 reloader: I1113 09:15:50.273591      23 util.go:45] failed to run cmd 
```

The associated line in haproxy.cfg is:
```
frontend http-443
	bind *:443  ssl no-sslv3 no-tlsv10 no-tls-tickets crt /etc/ssl/private/haproxy/tls/  alpn http/1.1
	# Mark all cookies as secure
	rsprep ^Set-Cookie:\ (.*) Set-Cookie:\ \1;\ Securemode http
```

When I remove the annotation `ingress.kubernetes.io/hsts`, the resulting haproxy.cfg is alright and haproxy is able to start.
