### ISSUE TITLE
How to use voyager instead of kubernetes nginx ingress controller

### ISSUE THREAD

**Issue by like-inspur** [appscode/voyager#742]
I install voyager on baremetal kubernetes according to with-rbac,yam, like this:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: voyager
  name: voyager-operator
  namespace: kube-system
spec:
  replicas: 1
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: voyager
  name: voyager-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: voyager
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: voyager-operator
      containers:
      - name: voyager
        args:
        - run
        - --v=3
        - --rbac
        - --analytics=false
        - --alsologtostderr=true
        - --ingress-class=voyager
        - --master=http://127.0.0.1:8080
        image: appscode/voyager:5.0.0-rc.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 56790
          name: ops
          protocol: TCP
        - containerPort: 56791
          name: acme
          protocol: TCP
      nodeSelector:
        manager: iop_true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
```
Then I create a voyager ingress , but after I config /etc/hosts, I can't access service according host/path
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: voyager
spec:
  rules:
  - host: appscode.example.com
    http:
      paths:
      - path: '/test'
        backend:
          serviceName: elasticsearch
          servicePort: '9200'
```
curl appscode.example.com/test
curl: (7) Failed connect to appscode.example.com:80; Connection refused

So how to use voyager as ingress controller, and where to find haproxy.cfg in voyager pod
