### ISSUE TITLE
create san cert with panic

### ISSUE THREAD

**Issue by gavinzhou** [appscode/voyager#744]
voyager 5.0.0.rc6 is worked in my gke
I will create san cert tls , get panic error

```
more g-certificate.yaml
apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: g-orangesys-cert
  namespace: apigateway
spec:
  domains:
  - demo.g.orangesys.io
  - fmsyon.g.orangesys.io
  acmeUserSecretName: stg-orangesys-user-secret
  challengeProvider:
    dns:
      provider: googlecloud
      credentialSecretName: saas-orangesys-io-gcp-secret
  storage:
    secret: {}
```

```
E1205 14:17:05.428930       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:367
/go/src/github.com/appscode/voyager/pkg/certificate/controller.go:251
/go/src/github.com/appscode/voyager/pkg/certificate/controller.go:151
/go/src/github.com/appscode/voyager/pkg/operator/certificate_crds.go:59
/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:195
<autogenerated>:1
/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:314
/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:150
/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:124
/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:124
/usr/local/go/src/runtime/asm_amd64.s:2337
```
