### ISSUE TITLE
Send proxy example

### ISSUE THREAD

**Issue by tamalsaha** [appscode/voyager#800]
HAProxy -> Nginx - . PHP

**Comment by aseroglazov** [comment]
Unfortunately documents are unclear how to setup `send-proxy` for backend.
Hope explanation below will help others to setup L4 ingress.
1) Create an L4 ingress (`mode tcp`)
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-voyager-ingress
  namespace: test-ns
  annotations:
    ingress.appscode.com/ssl-passthrough: "true"   # don't terminate ssl at voyager, forward it as is to backend.
                                                   # additionaly it turns mode from http to tcp
spec:
  frontendRules:                                   # these rules are optional. required to accept proxy protocol only from X.X.X.X
  - port: 80                                       # Applies all the rule in frontend section for port 80
    rules:                                         # rules to accept proxy protocol only from trusted sources
    - "acl trusted_proxy src X.X.X.X"
    - "tcp-request connection expect-proxy layer4 if trusted_proxy"
  rules:
  - host: example.com
    http:
      port: 80
      paths:
      - backend:
          serviceName: test-service
          servicePort: '80'
```
There is no `send-proxy` for backend yet.
2) Annotate **backend** service (Voyager will detect it and update ingress controller automatically):
`kubectl annotate svc test-service ingress.appscode.com/send-proxy="v1" -n test-ns`
That's it. After this action `send-proxy` appears in backend:
`# kubectl exec -ti voyager-test-voyager-ingress-6957668bcb-zjmk6 cat /etc/haproxy/haproxy.cfg`
```
# HAProxy configuration generated by https://github.com/appscode/voyager
# DO NOT EDIT!
global
        ...
defaults
        ...
frontend tcp-0_0_0_0-80
        bind *:80
        mode tcp
        acl trusted_proxy src X.X.X.X
        tcp-request connection expect-proxy layer4 if trusted_proxy
        default_backend test-service.test-ns:80
backend test-service.test-ns:80
        mode tcp
        server pod-test-66dc9869jzhxf 10.233.65.65:80     send-proxy
```
