### ISSUE TITLE
NodeAffinity/PodAffinity/nodeSelector are ignored when creating ReplicaSets

### ISSUE THREAD

**Issue by drf** [appscode/voyager#864]
Trying to create a Voyager Ingress in Voyager 5.0.11 with such a thing in its spec:

```yaml
nodeSelector:
  ingress-type: voyager
```

or

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: ingress-type
          operator: In
          values:
          - voyager
```

results in a ReplicaSet with no information whatsoever about affinity. In the first case, nodeSelector is simply not in the ReplicaSet spec, in the second, an empty NodeAffinity map appears in the ReplicaSet.
