### ISSUE TITLE
whitelist did not work

### ISSUE THREAD

**Issue by fragtom** [appscode/voyager#866]
added whitelist to voyager.appscode.com, resulted haproxy.cfg not valid.. 

```apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.appscode.com/replicas: "1"
    ingress.appscode.com/type: LoadBalancer
    ingress.kubernetes.io/whitelist-source-range: my.ip/32
```

with describe cm voyager-ingress-voyager the following rule seems ok for me, but not for haproxy 
```
frontend http-0_0_0_0-80
  bind *:80 
  mode http
  # Add whitelisted ips
  acl network_allowed src my.ip/32
  block if restricted_page !network_allowed
```

error message 

```
daemon.err: Feb 13 13:56:46 reloader: I0213 14:02:39.929513      43 mount_configmap.go:143] Processing change to ConfigMap ingress-voyager/voyager-ingress-voyager
daemon.err: Feb 13 13:56:46 reloader: I0213 14:02:39.929765      43 util.go:24] Mount Performed: 1
daemon.err: Feb 13 13:56:46 reloader: I0213 14:02:39.929786      43 util.go:40] calling boot file to execute
daemon.err: Feb 13 13:56:46 reloader: I0213 14:02:39.934735      43 util.go:43] Output:
daemon.err: Feb 13 13:56:46 reloader:  [ALERT] 043/140239 (1490) : parsing [/etc/haproxy/haproxy.cfg:34] : error detected while parsing an 'http-request block' condition : no such ACL : 'restricted_page'.
daemon.err: Feb 13 13:56:46 reloader: [ALERT] 043/140239 (1490) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
daemon.err: Feb 13 13:56:46 reloader: I0213 14:02:39.934765      43 util.go:45] failed to run cmd
```

any help appreciated.
container for voyager-operator
```
    spec:
      containers:
      - args:
        - run
        - --v=3
        - --cloud-provider=aws
        - --ingress-class=
        image: appscode/voyager:5.0.0-rc.11
```

**Comment by KresoDenis** [comment]
you can set IP whitelist on rule backend

```
          page:
            path: /page
            backend:
              service-name: page.page-namespace
              service-port: 80
              rules:
                - acl network_allowed src 22.22.22.22 33.33.33.33
                - block if !network_allowed
```
