### ISSUE TITLE
TCP Ingress: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rzal** [appscode/voyager#906]
```
voyager
Image:
appscode/voyager:5.0.0-rc.11
Environment variables:
-
Commands:
-
Args:
run
--v=3
--rbac=false
--cloud-provider=azure
--cloud-config=/etc/kubernetes/azure.json
--ingress-class=
--restrict-to-operator-namespace=false
```
```I0301 12:31:19.142631       1 parser.go:122] [b3623cbf-b8c6-4f48-bc80-e59afebe3058] Found target port 1883 for service my-nginx
E0301 12:31:19.143272       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```

```yaml
---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: deployment-ingress
  namespace: demo
spec:
  tls:
  - secretName: tls-secret
    hosts:
    - test.com
  rules:
  - host: test.com
    tcp:
      port: '7878'
      backend:
        serviceName: my-nginx
        servicePort: '1883'
```

The `operator` is throwing error if the ingress above is deployed shortly after the `operator` or when the number of pods belonging to the `my-nginx` service changes. After an error thrown the `operator` no longer updates the haproxy.conf `ConfigMap` 

This only occurs with if a TCP type Ingress is changing, but it affects HTTP ingresses once the `operator` has thrown an error.
