### ISSUE TITLE
Changing a backend block in the haproxy config (adding headers)

### ISSUE THREAD

**Issue by ofcourseican** [appscode/voyager#918]
Hi all,
I want to add a few headers to requests made to a specific backend. Looking at hack/docker/voyager/templates/http-backend.cfg I should be able to do something like this:

````
  rules:
  - host: jenkins.example.com
    http:
      paths:
      - backend:
          serviceName: jenkins-master
          servicePort: '80'
          headerRules:
          - 'X-Forwarded-Host jenkins.example.com'
          - 'X-Forwarded-Port 443 if { ssl_fc }'
          - 'X-Forwarded-Port 80 if { !ssl_fc }'
          - 'X-Forwarded-Proto https if { ssl_fc }'
````

But after applying this, the configmap I get with `kubectl describe configmap voyager-jenkins-master-ingress` stays like this:

```
backend jenkins-master.default:80
         server pod-jenkins-master-0 10.244.0.12:8080
```

I would want that to look like this:

```
backend jenkins-master.default:80
    server pod-jenkins-master-0 10.244.0.12:8080
    mode http
    option forwardfor
    http-request set-header X-Forwarded-Host jenkins.example.com
    http-request set-header X-Forwarded-Port 443 if { ssl_fc }
    http-request set-header X-Forwarded-Port 80 if { !ssl_fc }
    http-request set-header X-Forwarded-Proto https if { ssl_fc }
```

So how do I regenerate the configmap and get the haproxy to use the new config?

**Comment by tamalsaha** [comment]
Which version of Voyager are you using? I believe it should be `backends:` (plural).

**Comment by ofcourseican** [comment]
```
Version = 6.0.0-rc.2
VersionStrategy = tag
Os = alpine
Arch = amd64
CommitHash = caf30b35a5bf3e6a53b028f8e8b9499fb288eeb7
GitBranch = release-6.0
GitTag = 6.0.0-rc.2
CommitTimestamp = 2018-03-05T15:35:16
```

**Comment by tamalsaha** [comment]
I just tried it. Looks like a bug.

**Comment by tamalsaha** [comment]
@ofcourseican , I found the issue. It should be `headerRule` (singular).

I tried the following yaml and it worked:

```
#!/bin/bash

kubectl run nginx --image=nginx
kubectl expose deployment nginx --name=web --port=80 --target-port=80

kubectl run echoserver --image=gcr.io/google_containers/echoserver:1.4
kubectl expose deployment echoserver --name=rest --port=80 --target-port=8080

```

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    ingress.appscode.com/type: NodePort
    ingress.appscode.com/use-node-port: 'false'
spec:
  rules:
  - host: 'web.example.com'
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 80
          headerRule:
          - 'X-Forwarded-Host jenkins.example.com'
          - 'X-Forwarded-Port 443 if { ssl_fc }'
          - 'X-Forwarded-Port 80 if { !ssl_fc }'
          - 'X-Forwarded-Proto https if { ssl_fc }'
        path: /
  - host: '*.example.com'
    http:
      paths:
      - backend:
          serviceName: rest
          servicePort: 80
        path: /
```
