### ISSUE TITLE
HTTP to HTTPS redirect

### ISSUE THREAD

**Issue by Adiqq** [appscode/voyager#923]
Hi,

I had problem with HTTP to HTTPS redirect,

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: test-https-ingress
  namespace: default
  annotations:
    ingress.appscode.com/type: NodePort
    ingress.appscode.com/hsts: "false"
    ingress.appscode.com/force-ssl-redirect: "true"
spec:
  tls:
  - secretName: tls-secret
    hosts:
    - "*.a"
  rules:
  - host: "*.a"
    http:
      port: '32100'
      nodePort: '32100'
      paths:
      - backend:
          serviceName: httpbin
          servicePort: '8000'
  - host: "*.a"
    http:
      port: '32101'
      nodePort: '32101'
      paths:
      - backend:
          serviceName: httpbin2
          servicePort: '8000'
```

If i understand correctly, http://sample.a:32100 should redirect to https://sample.a:32100 with
 ```force-ssl-redirect: true``` ?

It works correctly if I add e.g.:
```
frontendRules:
  - port: 32100
    rules:
    - acl http      ssl_fc,not
    - http-request redirect scheme https if http
```
