### ISSUE TITLE
labels are not inherited to resources created via voyager Ingress

### ISSUE THREAD

**Issue by lilyhe123** [appscode/voyager#986]
This is my Voyager Ingress yaml file which has some labels settings, but the generated resources like pods, deployments, services etc don't have these labels.
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: domain3-voyager
  namespace: test1
  labels:
    label1: domain1
    label2: base_domain
  annotations:
    ingress.appscode.com/type: 'NodePort'
    ingress.appscode.com/stats: 'true'
spec:
  labels:
    label1: domain1
    label2: base_domain
  rules:
  - host: domain1.cluster-1
    http:
      nodePort: '30307'
      paths:
      - backend:
          serviceName: domain3-cluster-cluster-1
          servicePort: '8031'
```
